title: ManoaLink
subtitle: Company to Student Networking Made Easy
description: Easy Meetups in UH Manoa
logo: '/assets/images/ManoaLinkLogo.png'
github_username: uhmanoalink
minimal_mistakes_skin: dark

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom-feed:
  hide: true

footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/uhmanoalink'

defaults:
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
