title: ManoaLink
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: uhmanoalink
minimal_mistakes_skin: dark

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/uhmanoalink'

defaults:
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
